name: Continuous Integration
on: 
  pull_request:
    branches: [ master ]
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Download browsers for e2e testing
      run: npx playwright install

    - name: Run Unit Tests
      run: npm test

    - name: Run e2e Tests
      run: npm run e2e:ci

