name: Release
on:
  push:
    branches:
      - master
jobs:
  test:
      name: Tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Download browsers for e2e testing
        run: npx playwright install

      - name: Run Unit Tests
        run: npm test

      - name: Run e2e Tests
        run: npm run e2e:ci

      - name: Save run ID
        run: echo "${{ github.run_id }}" > run_id.txt

      - name: Upload run ID
        uses: actions/upload-artifact@v2
        with:
          name: run_id
          path: run_id.txt


  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'
          
      - name: Install Dependencies
        run: npm ci

      - name: Semantic Release
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Download run ID
        uses: actions/download-artifact@v2
        with:
          name: run_id

      - name: Create Release Issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./create-release-issue.sh ${{ secrets.GH_TOKEN }} $(cat run_id.txt)

  deploy:
    needs: release
    name: Deploy to GH-Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Project 
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true